### PR TITLE
fix for mapped values in v8/v9

### LINKED ISSUE #229: mappedValues/rangeMaps not working in v8.0 and v9
the workaround for v8/v9 ended up not processing valueMaps/rangeMaps correctly.

### PR DESCRIPTION
**Pull request by briangann**
To maintain compatibility back to Grafana >=v7.3, a wrapper is needed to process the value mappings based on the object passed in.

 * `getMappedValue()` function was removed in v9
 * the replacement `getValueMappingResult()` only appears in v8.1.0+

 At runtime, this cannot be reliably determined so the legacy function and the new function are both provided
 to allow this to work work across all versions (7.3 > 9.x).

Fixes #229

### CODE REVIEW

File: src/valueMappingsWrapper/index.ts [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+// At runtime, this cannot be determined so the legacy function and the new function are both provided
+// here, to allow this to work work across all versions (7.3 > 9.x)
+//
+export const GetMappedValue = (valueMappings: any[], value: any): any => {
+  let mappedValue = getMappedValue(valueMappings, value);
+  if (typeof mappedValue === 'undefined') {
+    return getValueMappingResult(valueMappings, value);
+  }
+  return mappedValue;
+};
```
Comment (leventebalogh) [inline src/valueMappingsWrapper/index.ts:20]: Nit: maybe you can use the [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) as well?

```suggestion
return getMappedValue(valueMappings, value) ?? getValueMappingResult(valueMappings, value);
};
```
